import {dedent, testPart} from '#lib/testing.js'

const input = dedent`
  .|...L....
  |.-.L.....
  .....|-...
  ........|.
  ..........
  .........L
  ..../.LL..
  .-.-/..|..
  .|....-|.L
  ..//.|....
`.replaceAll('L', '\\')

await testPart(import('./1.js?url'), [
  [input, 46],
  [
    dedent`
      .|...L....
      |.-.L.....
      .....|-...
      ........|.
      ..........
      .........L
      ..../.LL..
      .-.-/..|..
      .|....-|.L
      ..//.|....
      .|...L....
      |.-.L.....
      .....|-...
      ........|.
      ..........
      .........L
      ..../.LL..
      .-.-/..|..
      .|....-|.L
      ..//.|....
    `.replaceAll('L', '\\'),
    101,
  ],
])

await testPart(import('./2.js?url'), [input, 51])
